import { VerticalProject } from "@/components/VerticalProjectsRail";

export const vertical = (lang: string): VerticalProject[] => [
    {
        slug: "orbat-creator",
        title: "Orbat Creator",
        summary: "Role & slot editor with a clean UX for units and squads.",
        logoSrc: "/logos/orbat-c.png",
        href: `/${lang}/projects/orbat-creator/`,
        tags: ["Next.js", "TypeScript", "UX", "Design", "Brand", "Front-end"],
    },
    // {
    //     slug: "ambassade",
    //     title: "Ambassade de France en Autriche",
    //     summary: "Operations, events, and content system for a gaming community.",
    //     logoSrc: "/logos/amba-test-3d.png", // logoSrc: "/logos/amba-min-72.png",
    //     href: `/${lang}/projects/ambassade/`,
    //     tags: ["Administration des systèmes.", "GLPI"],
    // },
    {
        slug: "ambassade-",
        title: "Ambassade de France en Autriche",
        summary: "Operations, events, and content system for a gaming community.",
        logoSrc: "/logos/ministeres.png",
        href: `/${lang}/projects/ambassade/`,
        tags: ["Administration des systèmes.", "GLPI"],
    },
    {
        slug: "gese-platform",
        title: "GESE Platform",
        summary: "Operations, events, and content system for a gaming community.",
        logoSrc: "/logos/GESE-7e.png",
        href: `/${lang}/projects/gese-platform/`,
        tags: ["Content", "MDX", "Static"],
    },
    {
        slug: "cma",
        title: "CMA",
        summary: "Chambre des métiers et de l'artisanat.",
        logoSrc: "/logos/cma.png",
        href: `/${lang}/projects/cma/`,
        tags: ["Content", "MDX", "Static"],
    },
    {
        slug: "linkt",
        title: "Linkt",
        summary: "Internet provider B2B",
        logoSrc: "/logos/linkt.png",
        href: `/${lang}/projects/linkt/`,
        tags: ["Content", "MDX", "Static"],
    },
    {
        slug: "lery-poses",
        title: "Léry Poses",
        summary: "Nautical activities",
        logoSrc: "/logos/lery-g.png",
        href: `https://lery-poses.fr/`,
        tags: ["Content", "MDX", "Static"],
    },
    {
        slug: "promuseum",
        title: "Promuseum",
        summary: "Museum materials",
        logoSrc: "/logos/promuseum.png",
        href: `https://promuseum.eu/`,
        tags: ["Content", "MDX", "Static"],
    },
    {
        slug: "d-impulse",
        title: "D-Impulse",
        summary: "Consulting and digital agency.",
        logoSrc: "/logos/d-impulse.png",
        href: `/${lang}/projects/d-impulse/`,
        tags: ["Content", "MDX", "Static"],
    },
    {
        slug: "carrefour",
        title: "Carrefour Maxxing",
        summary: "Voucher system.",
        logoSrc: "/logos/carrefour.png",
        href: `/${lang}/projects/carrefour/`,
    },
];